# Generated by Django 4.2.2 on 2023-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='brokerage',
            new_name='corretagem',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='unit_price',
            new_name='preco_unitario',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity',
            new_name='quantidade',
        ),
        migrations.AlterField(
            model_name='stock',
            name='cnpj',
            field=models.CharField(help_text='Deve conter apenas números.', max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(help_text='Código de 4 letras maiúsculas seguidas de 1 ou 2 números.', max_length=6, unique=True),
        ),
    ]
