# Generated by Django 4.2.2 on 2023-06-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='risk_profile',
            new_name='perfil_de_risco',
        ),
    ]
